//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGE.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SISTEMA3;Initial Catalog=SGE_SERVICEN;User ID=sa;Password=123456")]
        public string SGE_SERVICENConnectionString {
            get {
                return ((string)(this["SGE_SERVICENConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sistema3;Initial Catalog=SVC_2;User ID=sa;Password=123456")]
        public string SVC_2ConnectionString {
            get {
                return ((string)(this["SVC_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SISTEMA3;Initial Catalog=SGE_SVC_2;User ID=sa;Password=123456")]
        public string SGE_SVC_2ConnectionString {
            get {
                return ((string)(this["SGE_SVC_2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sistema3;Initial Catalog=SGE_SVC_2;User ID=sa;Password=123456")]
        public string SGE_SVC_2ConnectionString1 {
            get {
                return ((string)(this["SGE_SVC_2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=sistemas2;Initial Catalog=SGE_JABSA;User ID=sa;Password=jair2006")]
        public string SGE_JABSAConnectionString {
            get {
                return ((string)(this["SGE_JABSAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_JABSA;Integrated Security=True")]
        public string SGE_JABSAConnectionString1 {
            get {
                return ((string)(this["SGE_JABSAConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LOCALHOST;Initial Catalog=SGE_JABSA;Integrated Security=True")]
        public string SGE_JABSAConnectionString2 {
            get {
                return ((string)(this["SGE_JABSAConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=SGE_JABSA;Integrated Security=True")]
        public string SGE_JABSAConnectionString3 {
            get {
                return ((string)(this["SGE_JABSAConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROGOLA-SERVER;Initial Catalog=jab;Integrated Security=True")]
        public string jabConnectionString {
            get {
                return ((string)(this["jabConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROGOLA-SERVER;Initial Catalog=SGE_JABSA;Integrated Security=True")]
        public string SGE_JABSAConnectionString4 {
            get {
                return ((string)(this["SGE_JABSAConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROGOLA-SERVER;Initial Catalog=SGE_CALZACOL;Integrated Security=True")]
        public string SGE_CALZACOLConnectionString {
            get {
                return ((string)(this["SGE_CALZACOLConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROGOLA-SERVER;Initial Catalog=SGE_JABSA_10_11.bak;Integrated Security" +
            "=True")]
        public string SGE_JABSA_10_11_bakConnectionString {
            get {
                return ((string)(this["SGE_JABSA_10_11_bakConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROGOLA-SERVER;Initial Catalog=SGE_PRECISION;Integrated Security=True")]
        public string SGE_PRECISIONConnectionString {
            get {
                return ((string)(this["SGE_PRECISIONConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ROGOLA-SERVER;Initial Catalog=SGE_DESCRISTIANO_v2;Integrated Security" +
            "=True")]
        public string SGE_DESCRISTIANO_v2ConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANO_v2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Sistemas1;Initial Catalog=SGE_DESCRISTIANO_v2;Integrated Security=Tru" +
            "e")]
        public string SGE_DESCRISTIANO_v2ConnectionString1 {
            get {
                return ((string)(this["SGE_DESCRISTIANO_v2ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Sistemas1;Initial Catalog=SGE_DESCRISTIANO_v3;Integrated Security=Tru" +
            "e")]
        public string SGE_DESCRISTIANO_v3ConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANO_v3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CATPO;Initial Catalog=SGE_DESCRISTIANOV2;Integrated Security=True")]
        public string SGE_DESCRISTIANOV2ConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANOV2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Sistemas1;Initial Catalog=SGE_DESCRISTIANO_v4;Integrated Security=Tru" +
            "e")]
        public string SGE_DESCRISTIANO_v4ConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANO_v4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=Sistemas1;Initial Catalog=SGE_DESCRISTIANO_v5;Integrated Security=Tru" +
            "e")]
        public string SGE_DESCRISTIANO_v5ConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANO_v5ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SISTEMAS1;Initial Catalog=SGE_DESCRISTIANO_v6;Integrated Security=Tru" +
            "e")]
        public string SGE_DESCRISTIANO_v6ConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANO_v6ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CATPO;Initial Catalog=SGE_DESCRISTIANO;Integrated Security=True")]
        public string SGE_DESCRISTIANOConnectionString {
            get {
                return ((string)(this["SGE_DESCRISTIANOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CATPO;Initial Catalog=SGE_DESARROLLOCRISTIANOFINAL;Integrated Securit" +
            "y=True")]
        public string SGE_DESARROLLOCRISTIANOFINALConnectionString {
            get {
                return ((string)(this["SGE_DESARROLLOCRISTIANOFINALConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CATPO;Initial Catalog=SGE_DESAROOLLO;Integrated Security=True")]
        public string SGE_DESAROOLLOConnectionString {
            get {
                return ((string)(this["SGE_DESAROOLLOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SISTEMAS1;Initial Catalog=SGE_DESCRISTIANO;Integrated Security=True")]
        public string SGE_DESCRISTIANOConnectionString1 {
            get {
                return ((string)(this["SGE_DESCRISTIANOConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_DESCRISTIANO;Integrated Security=True")]
        public string SGE_DESCRISTIANOConnectionString2 {
            get {
                return ((string)(this["SGE_DESCRISTIANOConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CATPO;Initial Catalog=SGE_PRECISION_V4;Integrated Security=True")]
        public string SGE_PRECISION_V4ConnectionString {
            get {
                return ((string)(this["SGE_PRECISION_V4ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_SERVIPARAMO;Integrated Security=True")]
        public string SGE_SERVIPARAMOConnectionString {
            get {
                return ((string)(this["SGE_SERVIPARAMOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_SERVIPARAMO_GERSON;Integrated Security=True")]
        public string SGE_SERVIPARAMO_GERSONConnectionString {
            get {
                return ((string)(this["SGE_SERVIPARAMO_GERSONConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_SERVIPARAMO1;Integrated Security=True")]
        public string SGE_SERVIPARAMO1ConnectionString {
            get {
                return ((string)(this["SGE_SERVIPARAMO1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_SERVIPARAMO2;Integrated Security=True")]
        public string SGE_SERVIPARAMO2ConnectionString {
            get {
                return ((string)(this["SGE_SERVIPARAMO2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_SERVIPARAMO_REAL;Integrated Security=True")]
        public string SGE_SERVIPARAMO_REALConnectionString {
            get {
                return ((string)(this["SGE_SERVIPARAMO_REALConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_SERVIPARAMO_COPIA;Integrated Security=True")]
        public string SGE_SERVIPARAMO_COPIAConnectionString {
            get {
                return ((string)(this["SGE_SERVIPARAMO_COPIAConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_PROPRECIO;Integrated Security=True")]
        public string SGE_PROPRECIOConnectionString {
            get {
                return ((string)(this["SGE_PROPRECIOConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_MJCGROUP;Integrated Security=True")]
        public string SGE_MJCGROUPConnectionString {
            get {
                return ((string)(this["SGE_MJCGROUPConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_MJCGROUP_SERVER;Integrated Security=True")]
        public string SGE_MJCGROUP_SERVERConnectionString {
            get {
                return ((string)(this["SGE_MJCGROUP_SERVERConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_MJCGROUP_SERVER2;Integrated Security=True")]
        public string SGE_MJCGROUP_SERVER2ConnectionString {
            get {
                return ((string)(this["SGE_MJCGROUP_SERVER2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.13;Initial Catalog=SGE_MJCGROUP;User ID=sa;Password=rogola2" +
            "012")]
        public string SGE_MJCGROUPConnectionString1 {
            get {
                return ((string)(this["SGE_MJCGROUPConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SIDE_I5;Initial Catalog=SGE_MJCGROUP;User ID=sa;Password=rogola2012")]
        public string SGE_MJCGROUPConnectionString2 {
            get {
                return ((string)(this["SGE_MJCGROUPConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SIDE;Initial Catalog=SGE_MJCGROUP;User ID=sa;Password=rogola2012")]
        public string SGE_MJCGROUPConnectionString3 {
            get {
                return ((string)(this["SGE_MJCGROUPConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SERVER;Initial Catalog=SGE_MJCGROUP;User ID=sa;Password=rogola2012")]
        public string SGE_MJCGROUPConnectionString4 {
            get {
                return ((string)(this["SGE_MJCGROUPConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO;Initial Catalog=SGE_MJCGROUP;User ID=sa;Password=rogola2012")]
        public string SGE_MJCGROUPConnectionString5 {
            get {
                return ((string)(this["SGE_MJCGROUPConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SIDE;Initial Catalog=SGE_MJCGROUP2;User ID=sa;Password=rogola2012")]
        public string SGE_MJCGROUP2ConnectionString {
            get {
                return ((string)(this["SGE_MJCGROUP2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LENOVO;Initial Catalog=SGE_PRADOS_VERDES;Integrated Security=True")]
        public string SGE_PRADOS_VERDESConnectionString {
            get {
                return ((string)(this["SGE_PRADOS_VERDESConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SGE_PRADOS_VERDES;Integrated Security=True")]
        public string SGE_PRADOS_VERDESConnectionString1 {
            get {
                return ((string)(this["SGE_PRADOS_VERDESConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:95.217.194.247,1433;Initial Catalog=sistemasintegrales_com_PV;Use" +
            "r ID=sistemasintegrales_com_de;Password=rogola2012")]
        public string sistemasintegrales_com_PVConnectionString {
            get {
                return ((string)(this["sistemasintegrales_com_PVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:95.217.194.247,1433;Initial Catalog=parquesdelparaiso_pe_PV;Persi" +
            "st Security Info=True;User ID=parquesdelparaiso_pe_de;Password=rogola2012")]
        public string parquesdelparaiso_pe_PVConnectionString {
            get {
                return ((string)(this["parquesdelparaiso_pe_PVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:95.217.194.247,1433;Initial Catalog=parquesdelparaiso_pe_PV;Persi" +
            "st Security Info=True;User ID=parquesdelparaiso_pe_de")]
        public string parquesdelparaiso_pe_PVConnectionString1 {
            get {
                return ((string)(this["parquesdelparaiso_pe_PVConnectionString1"]));
            }
        }
    }
}
